Repository BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce, pull requests merged in 2022-05, with the labels that each got.

#36 Feature#32/active storage
  Gemfile
  Gemfile.lock
  app/controllers/posts_controller.rb
  app/models/post.rb
  app/views/posts/_form.html.erb
  app/views/posts/_post.html.erb
  config/credentials.yml.enc
  config/environments/production.rb
  config/storage.yml
  db/migrate/20220427215121_create_active_storage_tables.active_storage.rb
  db/schema.rb
Labels: mentor review required, ready for review, review required

#39 Feature#33 crud comments
  app/controllers/post_comments_controller.rb
  app/views/post_comments/_form.html.erb
  app/views/post_comments/_post_comment.html.erb
  app/views/post_comments/new.html.erb
  app/views/posts/_comments.html.erb
  app/views/posts/show.html.erb
  config/routes.rb
  test/controllers/post_comments_controller_test.rb
  test/system/post_comments_test.rb
Labels: mentor review required, ready for review, review required

#40 Footer design was fixed
  app/assets/stylesheets/layout/_footer.scss
Labels: mentor review required, ready for review, review required

#38 Delete status id from permitted params
  app/controllers/posts_controller.rb
Labels: mentor review required, ready for review, review required

#45 Feature#42/update database
  app/models/order.rb
  app/models/post.rb
  app/models/post_comment.rb
  app/models/user_comment.rb
  db/migrate/20220412224233_create_user_comments.rb
  db/migrate/20220412224308_create_posts.rb
  db/migrate/20220412224434_create_post_comments.rb
  db/migrate/20220412224531_create_orders.rb
  db/schema.rb
Labels: mentor review required, ready for review, review required

#47 Feature#12/create the header layout
  app/assets/stylesheets/layout/_header.scss
  app/assets/stylesheets/utils/_variables.scss
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
Labels: mentor review required, ready for review, review required

#52 Feature#41/carousel products
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_cards.scss
  app/assets/stylesheets/components/_carousel.scss
  app/controllers/home_controller.rb
  app/views/home/_carousel.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/posts/_post_card.html.erb
  config/credentials.yml.enc
  yarn.lock
Labels: mentor review required, ready for review, review required

#57 Feature#34/deployment heroku
  config/credentials.yml.enc
  db/schema.rb
Labels: mentor review required, ready for review, review required

#54 Feature#30/style index page
  app/assets/images/Carousel.jpg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_cards.scss
  app/assets/stylesheets/components/_carousel_images.scss
  app/assets/stylesheets/components/_session_form.scss
  app/assets/stylesheets/pages/_index.scss
  app/views/home/_image_carousel.html.erb
  app/views/home/_user_navbar.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  package-lock.json
  yarn.lock
Labels: mentor review required, ready for review, review required

#59 Feature#53/syle product form
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_new_post_form.scss
  app/assets/stylesheets/utils/_variables.scss
  app/controllers/posts_controller.rb
  app/javascript/addItem.js
  app/models/post.rb
  app/views/layouts/application.html.erb
  app/views/posts/_form.html.erb
  app/views/posts/new.html.erb
Labels: mentor review required, ready for review, review required

#56 Feature#43/implement initial purchase system
  Gemfile
  Gemfile.lock
  app/controllers/order_controller.rb
  app/models/order.rb
  app/models/order_detail.rb
  app/models/user.rb
  app/views/orders/_buy_modal.html.erb
  app/views/orders/_form.html.erb
  app/views/orders/index.html.erb
  app/views/posts/_post_info.html.erb
  app/views/posts/show.html.erb
  config/routes.rb
  package.json
Labels: ready for review

#63 Feature#61/create pages routes
  Gemfile.lock
  app/controllers/users_controller.rb
  app/views/home/_user_navbar.html.erb
  app/views/users/favorites.html.erb
  app/views/users/messages.html.erb
  app/views/users/notifications.html.erb
  config/routes.rb
Labels: mentor review required, ready for review, review required

#76 Feature#73/modification migrations
  db/migrate/20220517002257_drop_reservations_table.rb
  db/migrate/20220517002406_drop_schedules_table.rb
  db/migrate/20220517002737_remove_type_columns.rb
  db/migrate/20220517002925_remove_picture_column_from_post.rb
  db/migrate/20220517003002_drop_types_table.rb
  db/migrate/20220517004500_add_delevery_to_post.rb
  db/schema.rb
  db/seeds.rb
Labels: mentor review required, ready for review, review required

#79 Feature#65/style function edit post
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_post_form.scss
  app/controllers/posts_controller.rb
  app/javascript/addItem.js
  app/models/post.rb
  app/models/type.rb
  app/models/user.rb
  app/views/posts/_form.html.erb
  app/views/posts/_post.html.erb
  app/views/posts/edit.html.erb
  app/views/posts/new.html.erb
  config/environments/development.rb
  db/migrate/20220412223459_create_types.rb
  db/schema.rb
  test/fixtures/types.yml
  test/models/type_test.rb
Labels: mentor review required, ready for review, review required

#78 Feature#60/add partial view component for sold products
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_scrollbar.scss
  app/assets/stylesheets/components/_sold_card.scss
  app/assets/stylesheets/layout/_user_navbar.scss
  app/assets/stylesheets/utils/_variables.scss
  app/controllers/order_controller.rb
  app/controllers/users_controller.rb
  app/javascript/application.js
  app/models/post.rb
  app/views/home/_user_navbar.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/orders/show.html.erb
  app/views/users/_sold_product.html.erb
  app/views/users/sold.html.erb
  config/routes.rb
Labels: ready for review

#84 Feature#44/shop view
  Gemfile.lock
  app/assets/images/german.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_purchases_card.scss
  app/assets/stylesheets/utils/_variables.scss
  app/controllers/users_controller.rb
  app/views/home/index.html.erb
  app/views/layouts/_header.html.erb
  app/views/layouts/application.html.erb
  app/views/users/_purchases_card.html.erb
  app/views/users/_purchases_list.html.erb
  app/views/users/purchases.html.erb
  config/routes.rb
Labels: mentor review required, ready for review, review required

#88 Add layouts for ranking
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_ranking.scss
  app/assets/stylesheets/pages/_post.scss
  app/controllers/posts_controller.rb
  app/views/post_comments/_ranking.html.erb
  app/views/posts/show.html.erb
Labels: ready for review

#93 Add logic to change functions if user not
  app/views/layouts/_header.html.erb
  db/schema.rb
Labels: mentor review required, ready for review, review required

#96 Products user done
  app/views/users/show.html.erb
  db/schema.rb
Labels: ready for review

#99 Feature#91/add styles to edit user
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_user_form_edit.scss
  app/assets/stylesheets/utils/_variables.scss
  app/controllers/application_controller.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
Labels: mentor review required, ready for review, review required

#81 Add styles for page recover-password
  app/assets/images/reset-password.svg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_buttons.scss
  app/assets/stylesheets/pages/_new_password.scss
  app/assets/stylesheets/utils/_variables.scss
  app/views/devise/passwords/new.html.erb
Labels: mentor review required, ready for review, review required

#100 Feature#92/add logic stock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_buy_modal.scss
  app/controllers/order_controller.rb
  app/models/order_detail.rb
  app/views/orders/_form.html.erb
Labels: ready for review

#104 Feature#69/layout styles profile
  app/assets/images/cover_default.png
  app/assets/images/default.jpg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_user_form_edit.scss
  app/assets/stylesheets/pages/_profile.scss
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
  app/views/users/profile.html.erb
  app/views/users/seller.html.erb
  config/routes.rb
Labels: mentor review required, ready for review, review required

#105 Feature#97/comments style
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_cards.scss
  app/assets/stylesheets/components/_info_post.scss
  app/assets/stylesheets/components/_ranking.scss
  app/assets/stylesheets/components/_reviews.scss
  app/assets/stylesheets/components/_stars.scss
  app/controllers/post_comments_controller.rb
  app/views/post_comments/_form.html.erb
  app/views/post_comments/_post_comment.html.erb
  app/views/post_comments/_ranking.html.erb
  app/views/posts/_comments.html.erb
  app/views/posts/_post_card.html.erb
  app/views/posts/_post_info.html.erb
Labels: ready for review

#103 Feature#71/add the sidebar
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/base/_globals.scss
  app/assets/stylesheets/components/_sold_card.scss
  app/assets/stylesheets/layout/_container_sidebar.scss
  app/assets/stylesheets/layout/_footer.scss
  app/assets/stylesheets/layout/_user_navbar.scss
  app/assets/stylesheets/pages/_profile.scss
  app/views/home/_user_navbar.html.erb
  app/views/users/favorites.html.erb
  app/views/users/profile.html.erb
  app/views/users/purchases.html.erb
  app/views/users/sold.html.erb
Labels: mentor review required, ready for review, review required

#89 Add styles for the "post comment" page to the product
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/base/_globals.scss
  app/assets/stylesheets/pages/_post_comment.scss
  app/assets/stylesheets/utils/_variables.scss
  app/controllers/post_comments_controller.rb
  app/views/layouts/_header.html.erb
  app/views/orders/show.html.erb
  app/views/post_comments/_form.html.erb
  app/views/post_comments/_post_comment.html.erb
  app/views/post_comments/new.html.erb
  app/views/users/_sold_product.html.erb
Labels: mentor review required, ready for review, review required

#109 Feature#108/connect purchases page with db
  app/assets/stylesheets/components/_buttons.scss
  app/assets/stylesheets/components/_purchases_card.scss
  app/assets/stylesheets/components/_session_form.scss
  app/assets/stylesheets/components/_sold_card.scss
  app/controllers/order_controller.rb
  app/controllers/users_controller.rb
  app/models/order.rb
  app/views/layouts/_header.html.erb
  app/views/orders/index.html.erb
  app/views/users/_purchases_card.html.erb
  app/views/users/_purchases_list.html.erb
  app/views/users/_sold_product.html.erb
  app/views/users/purchases.html.erb
  app/views/users/sold.html.erb
  config/routes.rb
Labels: ready for review

#90 Add styles for product purchase order note
  app/assets/stylesheets/components/_cards.scss
  app/assets/stylesheets/pages/_post_comment.scss
  app/assets/stylesheets/utils/_variables.scss
  app/views/orders/show.html.erb
Labels: mentor review required, review required

#113 Add styles for product post page
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/components/_cards.scss
  app/assets/stylesheets/components/_carousel.scss
  app/assets/stylesheets/components/_post_form.scss
  app/assets/stylesheets/pages/_posts.scss
  app/controllers/posts_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/kaminari/_first_page.html.erb
  app/views/kaminari/_gap.html.erb
  app/views/kaminari/_last_page.html.erb
  app/views/kaminari/_next_page.html.erb
  app/views/kaminari/_page.html.erb
  app/views/kaminari/_paginator.html.erb
  app/views/kaminari/_prev_page.html.erb
  app/views/posts/_form.html.erb
  app/views/posts/_post.html.erb
  app/views/posts/index.html.erb
  config/initializers/kaminari_config.rb
Labels: mentor review required, ready for review, review required

#116 Feature#115/search feature
  app/assets/images/empty.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_cards.scss
  app/assets/stylesheets/layout/_footer.scss
  app/assets/stylesheets/layout/_user_navbar.scss
  app/assets/stylesheets/pages/_profile.scss
  app/assets/stylesheets/pages/_search_post.scss
  app/controllers/home_controller.rb
  app/controllers/posts_controller.rb
  app/models/post.rb
  app/views/home/_user_navbar.html.erb
  app/views/home/results.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_header.html.erb
  app/views/posts/_comments.html.erb
  app/views/posts/_post.html.erb
  app/views/posts/_post_card.html.erb
  app/views/posts/index.html.erb
  app/views/users/messages.html.erb
  app/views/users/notifications.html.erb
  config/routes.rb
Labels: mentor review required, ready for review, review required

#118 Mis publicaciones was added
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_my_post_card.scss
  app/controllers/users_controller.rb
  app/views/home/_user_navbar.html.erb
  app/views/users/_my_product.html.erb
  app/views/users/posts.html.erb
  config/routes.rb
  db/schema.rb
Labels: mentor review required, ready for review, review required

#119 Feautre#95/shopping cart fun
  app/controllers/carts_controller.rb
  app/helpers/carts_helper.rb
  app/mailers/user_mailer.rb
  app/models/cart.rb
  app/models/post.rb
  app/views/carts/_cart_modal.html.erb
  app/views/carts/_form.html.erb
  app/views/carts/index.html.erb
  app/views/carts/show.html.erb
  app/views/layouts/_header.html.erb
  app/views/posts/_post_info.html.erb
  app/views/posts/show.html.erb
  config/routes.rb
  db/migrate/20220527130737_add_status_and_user_id_to_cart.rb
  db/schema.rb
  test/controllers/carts_controller_test.rb
Labels: mentor review required, ready for review, review required

#120 Feature#117/stock messages
  app/assets/stylesheets/components/_cards.scss
  app/assets/stylesheets/components/_info_post.scss
  app/assets/stylesheets/pages/_index.scss
  app/assets/stylesheets/pages/_post_comment.scss
  app/controllers/posts_controller.rb
  app/models/post.rb
  app/models/post_comment.rb
  app/views/home/index.html.erb
  app/views/orders/show.html.erb
  app/views/post_comments/_form.html.erb
  app/views/posts/_comments.html.erb
  app/views/posts/_post_info.html.erb
  app/views/posts/show.html.erb
  db/migrate/20220528003001_update_foreign_key_on_post_comments.rb
  db/migrate/20220528003114_update_foreign_key_on_order_details.rb
  db/migrate/20220528003152_update_foreign_key_on_favorites.rb
  db/schema.rb
Labels: mentor review required, ready for review, review required

#122 Fix error and hide buttons
  app/controllers/carts_controller.rb
  app/models/cart.rb
  app/views/layouts/_header.html.erb
Labels: mentor review required, ready for review, review required
